Fix user edit
chingu-voyage3/bears-20 pull request #14
Opened 2018-01-12 08:57 UTC by shibatas

* If user info is null (not logged in), it should now redirect to '/'.
* Even if user is logged in but skillset is not an array, it should now render the page.

2018-01-12 12:34 UTC, AlexGherardelli requested changes
I still have some issues with user profiles and logins, and I still haven't figured out exactly why these are happening. I do see that the code is spitting out helpful messages for debugging and it doesn't give that error with the null state, so I'm inclined to merge it with dev as is. One little thing: could you add the build folder to gitignore? I'd do it myself, but since it's so minor, it can be easily integrated in this PR!
Thanks :)

2018-01-12 20:44 UTC, shibatas commented
I added `build/` back into `gitignore`, and deleted the `build/` folder.
Regarding the login/logout issue that you're still having, can you try it with the Heroku deployment below?

<https://bears-20-dev.herokuapp.com/>

If you don't have issue there, then it's definitely something with your environment...

2018-01-13 14:52 UTC, AlexGherardelli approved these changes

2018-01-13 14:55 UTC, AlexGherardelli commented
It works perfectly on Heroku, so it's definitely a problem with my dev environment. Any idea on how to make sure these kind of problems are not happening in the future? I'm happy to use something as simple as Cloud9 (I remember you were using it) so at least we're running the same OS, but I'm also open to something more complicated like Vagrant or Docker - I've never used neither of these technologies, but I know that's one of the problems they're trying to solve, different dev environments/machines.

2018-01-13 14:55 UTC, merged